### ISSUE TITLE
ipscend screenshot

### ISSUE THREAD

**Issue by daviddias** [diasdavid/ipscend#2]
- [x] `ipscend screenshot` - open a gallery of all published versions with screenshots - https://github.com/diasdavid/ipsurge-preview
- [x] `ipscend screenshot --gen` - takes screenshot of all available hashes and add their hash to ipsurge.json versions
- [ ] make https://github.com/diasdavid/ipscend-screenshot-visualizer really fancy

Extra
~~\- [ ] --gif to generate the gif of all the screenshots (<- killer feature!!! :D )~~
Seems that to generate gifs in a Node.js context, it requires access for libgif to be installed. However, the browser already has this built it, so moving this feature to https://github.com/diasdavid/ipsurge-preview

**Comment by diasdavid** [comment]
TODO make --gen and --gif as subcommands instead of options

**Comment by daviddias** [comment]
update `renamed preview to screenshot`

**Comment by daviddias** [comment]
Looking for help in making the screenshot timeline preview look nice. An inspiration for it is making it have the same file of Apple's time machine:

![](http://km.support.apple.com/library/APPLE/APPLECARE_ALLGEOS/HT1427/en_US/HT1427_Star-field_004-en.png) 

Current:

![image](https://cloud.githubusercontent.com/assets/1211152/10413669/a0e606dc-6f67-11e5-8f1b-ce3872cd7bed.png)

Anyone is available to help? :)

**Comment by dignifiedquire** [comment]
I'll take a look what I can do :)

**Comment by dignifiedquire** [comment]
first draft 
![timeline-v1](https://cloud.githubusercontent.com/assets/790842/10439592/3b03fa42-713b-11e5-8bec-8e49e1b3526b.png)

**Comment by RichardLitt** [comment]
Those aren't jellyfish. 

No but seriously that looks awesome.

**Comment by daviddias** [comment]
Loooooks sweet! :smile: 

PS: cuttlefishes are more awesome than jellyfish :P 
![](http://www.leisurepro.com/blog/wp-content/uploads/2009/12/cuttlefish1.jpg)

**Comment by daviddias** [comment]
@Dignifiedquire did you had the chance to look at this again? Can't wait :):)

**Comment by jbenet** [comment]
that looks really good.

**Comment by jbenet** [comment]
where that = {@dignifiedquire's example, that cuttlefish}

**Comment by daviddias** [comment]
[update](https://www.dropbox.com/s/03oan2gmvudaxyt/Screenshot%202015-10-20%2011.43.30.png?dl=0)
still WIP

**Comment by dignifiedquire** [comment]
@diasdavid link is not working for me :(

**Comment by jbenet** [comment]
mmm try ipfs

**Comment by daviddias** [comment]
I was on a train, dropbox was the only thing that would do continuous syncing (which reminds me...), should work now, also: 
![image](https://cloud.githubusercontent.com/assets/1211152/10623135/1b330d50-7741-11e5-8bcc-cfd6695bec4c.png)

**Comment by jbenet** [comment]
nice!

**Comment by daviddias** [comment]
Found a timemachine.js library - https://github.com/stefanw/Canvas-Timemachine :D

**Comment by andresgutgon** [comment]
Working on CSS/JS version of @dignifiedquire mockup:

![image](https://cloud.githubusercontent.com/assets/49499/11168918/962373d4-8ba4-11e5-903f-a0746fc20919.png)

**Comment by daviddias** [comment]
@andresgutgon starting to look awesome!! :D

**Comment by jbenet** [comment]
wow this is very cool. i want to use it!

btw @diasdavid i think the ipscend data structure should use a commit object in ipfs-- something like https://github.com/ipfs/notes/issues/23 -- OR alternatively, import the history from git itself (maybe tag the commits constituting a published version).

**Comment by daviddias** [comment]
@jbenet that would be pretty sweet! You have my full attention, can we chat today about roadmap to make versioning part of IPFS? :D

**Comment by andresgutgon** [comment]
Working demo:
https://ipfs.io/ipfs/QmTVZxZMT5Cx3157fHkv16FY8PHYSJfy2xDhLdXXntkimw/

Still super WIP. I need to: 
1. Work on navigation UI (buttons for back/forward) versions
2. Connect with a real side (now are just images)
3. Move all code to a JS lib and make a class
4. Fix mouse will navigation.

The idea is to be able to move between versions with `mouse wheel/trackpad`, `arrow keys` and `UI`. Now it's only posible with arrow keys

**Comment by daviddias** [comment]
Awesomesauce! :D :D  I love fade animation. Are you still using timemachine.js or created your own lib?

**Comment by andresgutgon** [comment]
> Are you still using timemachine.js or created your own lib

It's just a bit of javascript and CSS :)

**Comment by andresgutgon** [comment]
Ok, I'm still working on it. I refactored the code into 2 files. `ipscend-version-getter.js` to make ipfs API call and `timemachine.js` that is managing UI logic to switch between versions.

Now is working with a real ipcsend site.
![ipscend-for-real](https://cloud.githubusercontent.com/assets/49499/11344725/3e54ffc2-9213-11e5-8c87-835a81d05a64.gif)

## TODO
- [ ] Add UI buttons to move `next` and `forward`.
- [ ] Add a header to display ipfs logo like in @Dignifiedquire mockup.

BTW. Someone can pass me an svg version of ipfs logo? Or do you have some kind of press page with corporative assets?

/cc @diasdavid @jbenet

**Comment by andresgutgon** [comment]
Also. Do a nice ipscend example to use as defaul :)

Maybe we could use https://ipfs.io/ home page to check evolution

**Comment by dignifiedquire** [comment]
@andresgutgon nice work :) logo assets can be found here: https://github.com/ipfs/logo

**Comment by andresgutgon** [comment]
Hi thanks @Dignifiedquire . I don't see `.svg` format. I'm not a designer and only have Inkscape installed. Do you knwo where I can find `.svg` version?

**Comment by andresgutgon** [comment]
PR done: https://github.com/diasdavid/ipscend-screenshot-visualizer/pull/1

**Comment by dignifiedquire** [comment]
@andresgutgon sorry there doesn't exist a vector version at the moment, you will have to make due with png for now. 
//cc @jbenet
